package validator

import (
	"errors"
	"math/big"
	"math/rand"
	"testing"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/accounts/abi/bind/backends"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/params"
	"github.com/stretchr/testify/require"

	"github.com/ethereum-optimism/optimism/op-service/testutils"
	"github.com/kroma-network/kroma/kroma-bindings/bindings"
)

// --- Test Constants ---

const (
	// TestChainID is a standard chain ID used for local testing environments.
	TestChainID = 1337
	// TestGenesisGasLimit defines the gas limit for the simulated backend.
	TestGenesisGasLimit = 50_000_000
	// TestTxGasLimit is a fixed gas limit used for the test transaction to disable estimation.
	TestTxGasLimit = 100_000
	// TestSeed is a fixed seed for deterministic random number generation.
	TestSeed = 1234
)

// toBigInt converts a uint64 to *big.Int for convenience in binding calls.
func toBigInt(u uint64) *big.Int {
	return new(big.Int).SetUint64(u)
}

// setupL2OutputOracle deploys the L2OutputOracle contract to a simulated backend,
// commits the transaction, and checks for successful deployment.
func setupL2OutputOracle() (common.Address, *bind.TransactOpts, *backends.SimulatedBackend, *bindings.L2OutputOracle, error) {
	privateKey, err := crypto.GenerateKey()
	if err != nil {
		return common.Address{}, nil, nil, nil, err
	}
	from := crypto.PubkeyToAddress(privateKey.PublicKey)

	opts, err := bind.NewKeyedTransactorWithChainID(privateKey, big.NewInt(TestChainID))
	if err != nil {
		return common.Address{}, nil, nil, nil, err
	}

	// Initialize the simulated blockchain with a large balance for the transactor
	backend := backends.NewSimulatedBackend(
		core.GenesisAlloc{from: {Balance: big.NewInt(params.Ether)}},
		TestGenesisGasLimit,
	)

	// Deploy L2OutputOracle contract using simple placeholder addresses
	_, tx, contract, err := bindings.DeployL2OutputOracle(
		opts,
		backend,
		common.Address{0x01}, // L2 Output Proposer (Placeholder)
		common.Address{0x02}, // L2 Output Challenger (Placeholder)
		common.Address{0x03}, // L2 Output Owner (Placeholder)
		big.NewInt(10),
		big.NewInt(2),
		big.NewInt(0),
		big.NewInt(0),
		big.NewInt(100),
	)
	if err != nil {
		return common.Address{}, nil, nil, nil, err
	}

	// CRITICAL: Commit the deployment transaction to the simulated backend
	backend.Commit()

	// Check the transaction receipt to ensure deployment was successful
	receipt, err := backend.TransactionReceipt(opts.Context, tx.Hash())
	if err != nil {
		return common.Address{}, nil, nil, nil, err
	}
	if receipt.Status != types.ReceiptStatusSuccessful {
		return common.Address{}, nil, nil, nil, errors.New("L2OutputOracle deployment failed on simulated backend")
	}

	return from, opts, backend, contract, nil
}

// TestManualABIPacking ensures that the manually packed transaction data for
// SubmitL2Output matches the data generated by the bound Go contract's function call.
// This is important because the actual transaction signing/sending logic may use
// the manual packing, and this test guarantees data consistency.
func TestManualABIPacking(t *testing.T) {
	// Note: The 'backend' is not used in this specific test, but is returned by setup.
	_, opts, _, contract, err := setupL2OutputOracle()
	require.NoError(t, err, "L2OutputOracle deployment failed")

	// Retrieve the contract ABI definition
	abi, err := bindings.L2OutputOracleMetaData.GetAbi()
	require.NoError(t, err, "Failed to get L2OutputOracle ABI")

	// Use a fixed seed for deterministic random data generation
	rng := rand.New(rand.NewSource(TestSeed))
	output := testutils.RandomOutputResponse(rng)

	// 1. Manually pack the transaction data using the external utility function
	txDataManual, err := SubmitL2OutputTxData(abi, output)
	require.NoError(t, err, "Manual ABI packing failed")

	// 2. Generate transaction data using the Go contract binding function
	// Set a gas limit to avoid reliance on gas estimation, which might fail 
	// because the full L2OO invariants are not upheld in this test.
	opts.GasLimit = TestTxGasLimit
	tx, err := contract.SubmitL2Output(
		opts,
		output.OutputRoot,
		toBigInt(output.BlockRef.Number),
		output.Status.CurrentL1.Hash,
		toBigInt(output.Status.CurrentL1.Number),
	)
	require.NoError(t, err, "Bound contract transaction creation failed")

	// 3. Verify that the manually packed data matches the bound contract's data
	require.Equal(t, txDataManual, tx.Data(), "Manually packed tx data must match bound contract tx data")
}
