name: Issue template
description: Report any issue or idea for this project to help us improve.
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue type
      description: What type of issue would you like to report?
      multiple: false
      options:
        - Bug
        - Build/Install
        - Performance
        - Support
        - Feature Request
        - Documentation Feature Request
        - Documentation Bug
        - Others
    validations:
      required: true

  - type: input
    id: kroma-version
    attributes:
      label: Kroma version
      placeholder: e.g. v1.0.1
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS platform and distribution
      placeholder: e.g. Linux Ubuntu 16.04
    validations:
      required: false

  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Type go version in terminal.
      placeholder: e.g. go1.19.3 linux/amd64
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node version
      description: Type node -v in terminal.
      placeholder: e.g. v16.14.2
    validations:
      required: false

  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior?
      description: Describe the bug or the problem related to a feature request.
      placeholder: A bug happened when I do something, or currently this feature is not supported.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior?
      description: What did you expect to happen?
      placeholder: A bug should not happen when I do something, or this feature should be supported.
    validations:
      required: true

  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Standalone code or description to reproduce the issue
      description: Provide a reproducible test case that is the bare minimum necessary to generate the problem.
      placeholder: Use this code, or follow these steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Please copy and paste any relevant log output. Or add any other context or screenshots about the feature request.
